import type { Metadata } from "next";
import "@/globals.css";
import Header from "@/components/dashboard/Header";
import { Roboto, Texturina } from "next/font/google";

const roboto = Roboto({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-roboto",
});

const texturina = Texturina({
  variable: "--font-texturina",
  display: "swap",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${texturina.variable} ${roboto.variable}`}>
      <body className={`antialiased max-w-7xl mx-auto bg-slate-800 md:px-10`}>
        <Header />

        {children}
      </body>
    </html>
  );
}
